services:
  auth-db:
    image: postgres:14
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - auth-net
    ports:
      - "5433:5432"

  auth-service:
    build: .
    container_name: auth-service
    restart: always
    env_file:
      - .env.prod
    environment:
      DB_NAME: auth_db
      DB_USER: postgres
      DB_PASSWORD: sksk0877
    ports:
      - "8001:8001"
    depends_on:
      - auth-db
    networks:
      - auth-net
      - schedule-auth-net

networks:
  auth-net:
    driver: bridge
  schedule-auth-net:
    external: true

volumes:
  auth-db-data:
