services:
  auth-db:
    image: postgres:14
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - auth-net
    ports:
      - "5432:5432"

  auth-service:
    build: .
    container_name: auth-service
    restart: always
    env_file:
      - .env.prod
    ports:
      - "8001:8001"
    depends_on:
      - auth-db
    networks:
      - auth-net

networks:
  auth-net:
    driver: bridge

volumes:
  auth-db-data:
